name : FunnY TexT Printer on a PR

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-Funny_Text:
    runs-on: ubuntu-latest
    permissions : write-all

    steps:
    
      - name: checkout
        uses: actions/checkout@v1
        
      - name: node.js setup
        uses : actions/setup-node@v3
        with :
            node-version : '14'
    
      - name: FunnyText
        run: node FunnyText.js
      -  name: Comment contributor's name
         uses: peter-evans/create-or-update-comment@v1
         with:
          issue-number: ${{ github.event.pull_request.number }}
          body: node FunnyText.js
          reactions: 'heart+1, hooray'
          
        
      
