name : FunnY TexT Printer on a PR

on: 
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print-Funny_Text:
    runs-on: ubuntu-latest

    steps:
    
      - name: checkout
        uses: actions/checkout@v2
        
      - name: node.js setup
        uses : actions/setup-node@v1
        with :
            node-version : '14'
    
      - name: FunnyText
        run: node FunnyText.js
